buildpipelinebeat:
  team: FallbackTeam
  status: Failure
  pipeline: fallbackPipeline
  project: fallbackProject
  error: None
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
